```{r}
library(tidyverse)
library(randomForest)
```

```{r}
train <- read.csv("D:/Projects/Phishing website detection/datasets/train.csv")
test <- read.csv("D:/Projects/Phishing website detection/datasets/test.csv")
```

```{r}
train <- train %>% 
  mutate(status = as.factor(status))
test <- test %>% 
  mutate(status = as.factor(status))
```

```{r}
model.rf <- randomForest(x = train %>% select(-status), y = train$status, ntree = 100)
```

```{r}
predictions <- predict(model.rf, test)
cm <- table(predictions, test$status)
accuracy <- (cm[1] + cm[4])/nrow(test) * 100
accuracy
cm[1]/(cm[1] + cm[2])
cm[1]/(cm[1] + cm[3])
```

With Hyper parameter tuning

```{r}
library('e1071')
library('parsnip')
library('ranger')
library('tidyverse')
library('pso')
```

```{r}
#PSO Optimisation

#Defining fitness function
fit_function <- function(x){
  a <- as.integer(x[1])
  
  #define model
  model <- randomForest(x = train %>% select(-status), y = train$status, ntree=a)
  
  preds <- predict(model, test)
  cm <- table(preds, test %>% pull('status'))
  acc <- (cm[1] + cm[4])/nrow(test)
  return(-acc)
}
```

```{r}
pso <- psoptim(par = rep(NA,1), fn = fit_function, lower = c(10), upper = c(500), 
        control = list(maxit = 20, vectorize = T, s = 2))
pso$par
```

New Model

```{r}
a <- as.integer(pso$par[1])

#define model
model <- randomForest(x = train %>% select(-status), y = train$status, ntree=a)

preds <- predict(model, test)
cm <- table(preds, test %>% pull('status'))
acc <- (cm[1] + cm[4])/nrow(test)
acc
cm[1]/(cm[1] + cm[2])
cm[1]/(cm[1] + cm[3])
```

Without Hypertuning - 0.9571429
With hypertuning - 0.9591837



